// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlszizavjjlswxsbqgqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsc3ppemF2ampsc3d4c2JxZ3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDc1MDgsImV4cCI6MjA2NzQyMzUwOH0.s3FT3Yl92ViuacsT7co1Uka6iggJtA3NhfjLN8F4dkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});