// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dalztfnfbzagbdmbfdrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhbHp0Zm5mYnphZ2JkbWJmZHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzU1MDksImV4cCI6MjA2NzU1MTUwOX0.GZUnmmHQZM_ssumZyrFsvEna2aNZ_Njz3fEEAZKEh_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});